export const NEW_DECK_REQUEST = 'NEW_DECK_REQUEST';
export const NEW_DECK_FAILURE = 'NEW_DECK_FAILURE';
export const NEW_DECK_SUCCESS = 'NEW_DECK_SUCCESS';
export const UPDATE_REMAINING = 'UPDATE_REMAINING';
