export const DRAW_CARDS_REQUEST = 'DRAW_CARDS_REQUEST';
export const DRAW_CARDS_FAILURE = 'DRAW_CARDS_FAILURE';
export const DRAW_CARDS_SUCCESS = 'DRAW_CARDS_SUCCESS';
export const REVEAL_RESULT = 'REVEAL_RESULT';
export const RESET_GAME = 'RESET_GAME';
